# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthaber',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news-images', verbose_name='Fotoğraf'),
        ),
    ]
