# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logocarousel',
            options={'verbose_name': 'Logo Carousel Görseli', 'verbose_name_plural': 'Logo Carousel Görselleri'},
        ),
        migrations.AlterModelOptions(
            name='rightbannerbottom',
            options={'verbose_name': 'Sağ Alt Banner', 'verbose_name_plural': 'Sağ Alt Banner Görselleri'},
        ),
        migrations.AlterModelOptions(
            name='rightbannertop',
            options={'verbose_name': 'Sağ Üst Banner', 'verbose_name_plural': 'Sağ Üst Banner Görselleri'},
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name': 'Slider Görseli', 'verbose_name_plural': 'Slider Görselleri'},
        ),
    ]
