# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Yazarın Adı-Soyadı')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='author-img', verbose_name='Fotoğrafı')),
            ],
        ),
        migrations.CreateModel(
            name='PostYazar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news-images', verbose_name='Fotoğraf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yazarlar.Author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
