# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yazarlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Yazar', 'verbose_name_plural': 'Yazarlar'},
        ),
        migrations.AlterModelOptions(
            name='postyazar',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gönderi', 'verbose_name_plural': 'Yazar Gönderileri'},
        ),
    ]
